root/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.views.static import serve

from root.settings import ENVIRONMENT, MEDIA_ROOT, STATIC_ROOT
from src.core.handlers import (
    handler404, handler500
)

urlpatterns = []

""" HANDLERS ------------------------------------------------------------------------------------------------------- """
handler404 = handler404
handler500 = handler500

""" INTERNAL REQUIRED APPS ----------------------------------------------------------------------------------------- """
urlpatterns += [
    path('', include('src.web.urls')),
    path('', include('src.api.urls')),
    path('', include('src.apps.whisper.urls')),
]

""" EXTERNAL REQUIRED APPS ----------------------------------------------------------------------------------------- """
urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),

]

""" STATIC AND MEDIA FILES ----------------------------------------------------------------------------------------- """
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

""" DEVELOPMENT ONLY -------------------------------------------------------------------------------------------- """
if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

    urlpatterns += [
        path('', TemplateView.as_view(template_name='dev/starter-page.html')),  # use: for home page/remove this
    ]

src/web/admins/urls.py
from django.urls import path
from .views import (
    DashboardView,
    UserListView, UserPasswordResetView, UserDetailView, UserUpdateView, SocialsView, remove_social_account
)


app_name = 'admins'
urlpatterns = [

    path('', DashboardView.as_view(), name='dashboard'),

    path('user/', UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/change/', UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/password/reset/', UserPasswordResetView.as_view(), name='user-password-reset-view'),

    path('socials/', SocialsView.as_view(), name='social-accounts'),
    path('remove-social-auth/<int:account_id>/', remove_social_account, name='remove_social_account'),

]

src/web/admins/templates/admins/admin_password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block subtitle %}
    Password Reset
{% endblock %}


{% block content %}

    <div class="row">
        <div class="col-sm-12">
        <p><a href="{% url 'admins:user-detail' object.id %}"><i class="fa fa-arrow-left"></i> Go Back</a></p>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">

                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}

                        <div class="mt-3">
                            <button type="submit" class="btn-sm btn-primary">
                                Submit
                            </button>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/web/admins/templates/admins/social-accounts.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load socialaccount %}  <!-- Load the socialaccount tags -->


{% block subtitle %} {{ request.user }} {% endblock %}

{% block content %}
<div class="container ">
    <div class="row">
        <div class="col-md-6">
            <div class="card border-0 shadow-sm mb-3" style="border-radius: 1rem;">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">Connected Social Accounts</h2>
                    <p class="card-text text-center">You are connected to the following social accounts.</p>

                    {% if social_accounts %}
                    <div class="row">
                        {% for account in social_accounts %}
                        <div class="col-md-12">
                            <div class="card   rounded shadow-sm mb-3"
                                 style="border-radius: 1rem; border-style: solid;">
                                <div class="card-body d-flex justify-content-between align-items-center">
                                    <h5 class="card-title btn btn-success mb-0">{{ account.provider }} Connected</h5>
                                    <a href="{% url 'admins:remove_social_account' account.id %}"
                                       class="btn btn-outline-danger"
                                       onclick="return confirm('Are you sure you want to remove this account?');">Remove
                                    </a>
                                </div>
                                <pre>{{ account.extra_data|json_script:"extra_data" }}</pre>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    {% else %}
                    <div class="d-flex justify-content-center"><p>No social accounts connected.</div>


                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card border-0 shadow-sm mb-3" style="border-radius: 1rem;">
                <div class="card-body">
                    <h3 class="card-title text-center mb-4">Link Your Account</h3>

                    <a href="{% provider_login_url 'Google' process='connect'  %}"
                       class="btn btn-outline-danger m-2 btn-lg btn-block">
                        <i class="bx bxl-google"></i> Connect Google
                    </a>
                    <a href="#" class="btn btn-outline-dark m-2 btn-lg btn-block">
                        <i class="bx bxl-apple"></i>  Connect Apple
                    </a>

                </div>
            </div>
        </div>
    </div>
        <div class="account-settings p-3 m-4">
            <h2>Account Security - 2FA</h2>
                <p>Enhance the security of your account by setting up Two-Factor Authentication.</p>
            <a href="{% url 'mfa_index' %}" class="btn btn-danger">Set Up Two-Factor Authentication</a>
        </div>
</div>

{% endblock %}

src/web/admins/templates/admins/user_detail.html
{% extends 'base.html' %}
{% load static %}
{% load core_tags %}

{% block subtitle %}
    {{ user.username }}
{% endblock %}


{% block content %}

    <div class="row">
        <div class="col-sm-12">
            <p><a href="{% url 'admins:user-list' %}"><i class="fa fa-arrow-left"></i> Go Back</a></p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    {# IMAGE DIV #}
                    <div class="text-center">
                        {% if user.profile_image %}
                            <img class="rounded-circle" src="{{ user.profile_image.url }}" height="150px"
                                 alt="user-image">
                        {% else %}
                            <img class="rounded-circle" src="{% static 'core/images/base/no-user.png' %}"
                                 height="150px" alt="no-user-image">
                        {% endif %}
                    </div>

                    {# NAME AND OTHER #}
                    <div class="text-center mt-2">
                        <h5 class="mb-0">
                            {{ user.get_full_name }} - ( {{ user.username }} )
                            {% if user.is_active %}
                                <i class="fa fa-check-circle text-success"></i>
                            {% endif %}
                        </h5>
                        <p class="fw-light text-muted mb-0">registered on > {{ user.date_joined }}</p>
                    </div>

                    <div class="row mt-4">
                        <div class="col">
                            <p class="mb-0 text-center h3"><i class="mdi mdi-email"></i></p>
                            <p class="mb-0 text-center h5">Email</p>
                            <p class="mb-0 text-center">{{ user.email }}</p>
                        </div>
                        <div class="col">
                            <p class="mb-0 text-center h3"><i class="mdi mdi-phone"></i></p>
                            <p class="mb-0 text-center h5">Phone</p>
                            <p class="mb-0 text-center">{{ user.phone_number }}</p>
                        </div>
                        <div class="col text-center">
                            <p class="mb-0 text-center h3"><i class="mdi mdi-shield-account"></i></p>
                            <p class="mb-0 text-center h5">Access Level</p>
                            <p class="mb-0 text-center">
                                <b>
                                    {% if user.is_superuser and user.is_staff %}
                                        Admin
                                    {% elif user.is_staff %}
                                        Staff
                                    {% else %}
                                        User
                                    {% endif %}
                                </b>
                            </p>
                        </div>
                        <div class="col text-center">
                            <p class="mb-0 text-center h3"><i class="mdi mdi-security"></i></p>
                            <p class="mb-0 text-center h5">Last Login</p>
                            <p class="mb-0 text-center">{{ user.last_login }}</p>
                        </div>

                        <div class="col">
                            <p class="mb-0 text-center h3"><i class="fa fa-user-edit"></i></p>
                            <p class="mb-0 text-center h5">Profile</p>
                            <p class="mb-0 text-center">
                                <a href="{% url 'admins:user-update' user.pk %}">Update</a>
                            </p>
                        </div>

                        <div class="col">
                            <p class="mb-0 text-center h3"><i class="fa fa-user-lock"></i></p>
                            <p class="mb-0 text-center h5">Password</p>
                            <p class="mb-0 text-center text-danger">
                                <a href="{% url 'admins:user-password-reset-view' user.pk %}">Change</a>
                            </p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    {# STATISTICS #}
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body border-bottom">
                    <p class="card-title mb-0">User Statistics</p>
                </div>
                <div class="card-body">

                    {% if statistic %}
                        <div class="row">

                            <div class="col border-right">
                                <p class="mb-0 text-center h3 text-success"><i class="mdi mdi-arrow-up"></i></p>
                                <p class="mb-0 text-center small">Current TRX</p>
                                <p class="mb-0 text-center h4">00</p>
                            </div>

                            <div class="col">
                                <p class="mb-0 text-center h3 text-danger"><i class="mdi mdi-arrow-down"></i>
                                </p>
                                <p class="mb-0 text-center small">Withdrawal TRX</p>
                                <p class="mb-0 text-center h4">00</p>
                            </div>

                            <div class="col">
                                <p class="mb-0 text-center h3"><i class="fa fa-coins text-warning"></i></p>
                                <p class="mb-0 text-center small">Generated TRX</p>
                                <p class="mb-0 text-center h4">00</p>
                            </div>

                        </div>
                    {% else %}
                        <p class="text-danger h4 mb-0">Statistics are not available for this account - please
                            consult
                            developers</p>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>


{% endblock %}

src/web/admins/templates/admins/user_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load core_tags %}

{% block subtitle %}
    Users List
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <form method="get">
                <div class="input-group mb-3">
                    {{ user_filter_form }}
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                            <i class="fa fa-search"></i> Search
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">


                    <div class="table-responsive">
                        <table class="table table-borderless">
                            {% if user_list %}
                                <thead class="border-bottom">
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Username</th>
                                    <th>Email</th>
                                    <th>
                                        Package
                                    </th>
                                    <th>Referred By</th>
                                    <th>Active</th>
                                    <th>Action</th>
                                </tr>
                                </thead>

                                <tbody>

                                {% for user in user_list %}
                                    <tr>
                                        <td>{{ user.pk }}</td>
                                        <td>{{ user.first_name }} {{ user.last_name }}</td>
                                        <td>{{ user.username }}</td>
                                        <td>{{ user.email }}</td>
                                        <td>
                                            {% if not user.current_subscription %}
                                                <b class="text-danger"><i class="fa fa-times-circle"></i> Free</b>
                                            {% else %}
                                                <b class="text-success">
                                                    <i class="fa fa-check-circle"></i> {{ user.current_subscription.package.name }}
                                                </b>
                                            {% endif %}
                                        </td>
                                        <td>

                                            {% if user.referred_by %}
                                                <b>
                                                    <a href="{% url 'admins:user-detail' user.referred_by.pk %}">
                                                        {{ user.referred_by.username }}
                                                    </a>
                                                </b>
                                            {% else %}
                                                <b class="text-danger">
                                                    None
                                                </b>
                                            {% endif %}

                                        </td>
                                        <td>
                                            {% if user.is_active %}
                                                <b class="text-success"><i class="fa fa-check-circle"></i></b>

                                            {% else %}
                                                <b class="text-danger"><i class="fa fa-times-circle"></i></b>

                                            {% endif %}
                                        </td>

                                        <td>
                                            <a href="{% url 'admins:user-detail' user.pk %}"
                                               class="text-decoration-none"><i
                                                    class="mdi mdi-eye icon-sm"></i> View
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            {% else %}
                                <th class="text-danger">No users data available.</th>
                            {% endif %}
                        </table>
                    </div>


                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="mt-4">
                <ul class="pagination">
                    {% if user_list.has_previous %}
                        <li>
                            <span>
                                <a href="{% relative_url user_list.previous_page_number 'page' request.GET.urlencode %}">
                                    Previous
                                </a>
                            </span>
                        </li>
                    {% endif %}
                    <li class="">
                        <span>Page {{ user_list.number }} of {{ user_list.paginator.num_pages }}.</span>
                    </li>
                    {% if user_list.has_next %}
                        <li>
                            <span>
                                <a href="{% relative_url user_list.next_page_number 'page' request.GET.urlencode %}">
                                    Next
                                </a>
                            </span>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

{% block js_code %}
    <script>
        $(document).ready(function () {

            $('label').hide();
            $('input').addClass('form-control');
            $('select').addClass('form-control');

        });
    </script>
{% endblock %}

src/web/admins/templates/admins/user_update_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block subtitle %}
    Update {{ object.username }}
{% endblock %}


{% block content %}

    <div class="row">
        <div class="col-sm-12">
        <p><a href="{% url 'admins:user-detail' object.pk %}"><i class="fa fa-arrow-left"></i> Go Back</a></p>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card p-4">
                <div class="card-body">

                    <div class="">
                        {% if form.instance.profile_image %}
                            <img class="rounded-circle" src="{{ form.instance.profile_image.url }}" height="150px" alt="user-image">
                        {% else %}
                            <img class="rounded-circle" src="{% static 'core/images/base/no-user.png' %}"
                                 height="150px" alt="no-user-image">
                        {% endif %}
                    </div>

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        {{ form|crispy }}
                        <div class="">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}