root/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.views.static import serve

from root.settings import ENVIRONMENT, MEDIA_ROOT, STATIC_ROOT
from src.core.handlers import (
    handler404, handler500
)

urlpatterns = []

""" HANDLERS ------------------------------------------------------------------------------------------------------- """
handler404 = handler404
handler500 = handler500

""" INTERNAL REQUIRED APPS ----------------------------------------------------------------------------------------- """
urlpatterns += [
    path('', include('src.web.urls')),
    path('', include('src.api.urls')),
    path('', include('src.apps.whisper.urls')),
]

""" EXTERNAL REQUIRED APPS ----------------------------------------------------------------------------------------- """
urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),

]

""" STATIC AND MEDIA FILES ----------------------------------------------------------------------------------------- """
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

""" DEVELOPMENT ONLY -------------------------------------------------------------------------------------------- """
if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

    urlpatterns += [
        path('', TemplateView.as_view(template_name='dev/starter-page.html')),  # use: for home page/remove this
    ]

src/apps/whisper/urls.py
from django.urls import path

from src.apps.whisper.views import (
    EmailNotificationListView, EmailNotificationRetryView)

app_name = 'whisper'

urlpatterns = [
    path('email/list/', EmailNotificationListView.as_view(), name='emailnotification-list'),
    path('email/<str:pk>/retry/', EmailNotificationRetryView.as_view(), name='emailnotification-retry'),

]

src/apps/whisper/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

STATUS_CHOICES = [
    ('pending', 'Pending'),
    ('sent', 'Sent'),
    ('failed', 'Failed'),
    ('retry', 'Retry'),
]


class EmailNotification(models.Model):
    subject = models.CharField(max_length=255)
    body = models.TextField()
    recipient = models.EmailField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    failed_attempts = models.PositiveIntegerField(default=0)
    template_name = models.CharField(max_length=255, blank=True, null=True)
    error_message = models.TextField(blank=True, null=True)  # New field

    # Generic foreign key to relate this model to any other model
    content_type = models.ForeignKey(ContentType, on_delete=models.SET_NULL, blank=True, null=True)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Email to {self.recipient} at {self.updated_at if self.updated_at else 'Not Sent'}"

src/apps/whisper/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, View

from src.apps.whisper.filters import EmailNotificationFilter
from src.apps.whisper.main import NotificationService
from src.apps.whisper.models import EmailNotification



class EmailNotificationListView( ListView):
    model = EmailNotification
    template_name = 'whisper/emailnotification_list.html'

    def get_permission_name(self):
        return "whisper.view_emailnotification"

    def get_queryset(self):
        return self.model.objects.order_by('created_at')

    def get_context_data(self, **kwargs):
        context = super(EmailNotificationListView, self).get_context_data(**kwargs)
        email_filter = EmailNotificationFilter(self.request.GET, queryset=self.get_queryset())
        context['filter_form'] = email_filter.form

        paginator = Paginator(email_filter.qs, 50)
        page_number = self.request.GET.get('page')
        user_page_object = paginator.get_page(page_number)

        context['object_list'] = user_page_object
        return context


class EmailNotificationRetryView(View):
    def get_permission_name(self):
        return "whisper.change_emailnotification"

    def get(self, request, *args, **kwargs):
        email_notification_id = kwargs.get('pk')
        email_notification = get_object_or_404(EmailNotification, id=email_notification_id)

        notification_service = NotificationService(
            heading=email_notification.subject,
            description=email_notification.body,
            obj=email_notification.content_object,
            retry_id=email_notification.id,
            recipient_list=[email_notification.recipient]
        )

        context = {
            'body': email_notification.body
        }

        # Retry sending the email
        notification_service.send_email_notification(email_notification.template_name, context,
                                                     [email_notification.recipient])

        return redirect('whisper:emailnotification-list')

src/apps/whisper/templates/whisper/base.html
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<body style="background-color: white;color: #3f3f3f">
<table class="body-wrap"
       style="font-family: 'Helvetica Neue',
       Helvetica,Arial,sans-serif; box-sizing:
       border-box; font-size: 14px; width: 100%; margin: 0;">
    <tbody>
    <tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
        <td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;"
            valign="top"></td>
        <td class="container" width="600"
            style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; display: block !important; max-width: 800px !important; clear: both !important; margin: 0 auto;"
            valign="top">
            <div class="content"
                 style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; max-width: 800px; display: block; margin: 0 auto; padding: 20px;">
                <table class="main" width="100%" cellpadding="0" cellspacing="0" itemprop="action" itemscope=""
                       itemtype="http://schema.org/ConfirmAction"
                       style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; border-radius: 3px; margin: 0; "
                >
                    <tbody>
                    <tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
                        <td class="content-wrap"
                            style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 20px;"
                            valign="top">
                            <meta itemprop="name" content="Confirm Email"
                                  style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
                            <table width="100%" cellpadding="0" cellspacing="0"
                                   style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
                                <tbody>

                                {% block header %}
                                    <tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
                                        <td class="content-block"
                                            style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; color: #5766da; font-size: 24px; font-weight: 700; vertical-align: top; margin: 0; padding: 0 0 10px;"
                                            valign="top">
                                            <img src='https://fldai.s3.amazonaws.com/static/website/images/header_logo.png'/>
                                        </td>
                                    </tr>

                                {% endblock %}
                                <tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 16px; margin: 0;">
                                    <td>
                                        {% block content %}


                                        {% endblock %}
                                    </td>
                                </tr>

                                {% block footer %}
                                    <tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
                                        <td class="content-block"
                                            style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 16px; padding-top: 0px; vertical-align: top; margin: 0; text-align: left;"
                                            valign="top">
                                            <p>
                                                Best regards
                                            </p>
                                            <p>
                                                <a style="font-size: 18px;"
                                                   href="mailto:support@first-linedefense.org">
                                                    FLD - Support Team
                                                </a>
                                            </p>
                                        </td>
                                    </tr>
                                {% endblock %}
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    </tbody>
                </table><!--end table--></div><!--end content--></td>
        <td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;"
            valign="top"></td>
    </tr>
    </tbody>
</table>
</body>
</html>

src/apps/whisper/templates/whisper/emailnotification_list.html
{% extends 'base_content.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load core_tags %}

{% block subtitle %}
    Emails
{% endblock %}

{% block content_head_title %}
    Email Management
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-12">
            <form method="get">
                <div class="input-group mb-3">
                    {{ filter_form }}
                    <div class="input-group-append">
                        <button class="btn btn-lg d-block btn-outline-theme" type="submit">
                            <i class="fa fa-search"></i> Search
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            <div class="card border-0">
                <div class="card-body px-0">
                    <div class="table-responsive">
                        <table class="table table-hover table-borderless">
                            {% if object_list %}
                                <thead class="border-bottom">
                                <tr>
                                    <th>ID</th>
                                    <th>Subject</th>
                                    <th>Recipient</th>
                                    <th>Status</th>
{#                                    <th>Failed Attempts</th>#}
                                    <th>Created at</th>
                                    <th>Active</th>
                                </tr>
                                </thead>

                                <tbody>

                                {% for object in object_list %}
                                    <tr>
                                        <td>{{ object.pk }}</td>
                                        <td>{{ object.subject }}</td>
                                        <td>{{ object.recipient }}</td>
                                        <td>
                                            <span class="badge bg-{{ object.status|alert_type_class }}">
                                                <b>
                                                    {% if object.status == "sent" %}
                                                        <i class="fa fa-check-circle"></i>
                                                    {% else %}
                                                        <i class="fa fa-times-circle"></i>
                                                    {% endif %}
                                                    {{ object.status }}
                                                </b>

                                            </span>

                                            {% if object.status == 'failed' %}
                                                 | <i class="fa fa-eye text-danger"
                                                   data-object-value="{{ object.error_message }}"
                                                   onclick="showError(this)"></i>
                                            {% endif %}
                                        </td>

{#                                        <td class="text-center">{{ object.failed_attempts }}</td>#}
                                        <td>{{ object.created_at.date|check_null }}</td>


                                        <td>
                                            {% if request.user.is_superuser or perms.whisper.change_emailnotification %}

                                                <a href="{% url 'whisper:emailnotification-retry' object.pk %}"
                                                   class="text-decoration-none"><i
                                                        class="fa fa-repeat"></i> Retry
                                                </a>
                                            {% else %}
                                                -
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            {% else %}
                                <th class="text-danger">No Emails data available.</th>
                            {% endif %}
                        </table>
                    </div>


                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="mt-4">
                <ul class="pagination">
                    {% if object_list.has_previous %}
                        <li>
                            <span>
                                <a href="{% relative_url object_list.previous_page_number 'page' request.GET.urlencode %}">
                                    Previous
                                </a>
                            </span>
                        </li>
                    {% endif %}
                    <li class="">
                        <span>Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.</span>
                    </li>
                    {% if object_list.has_next %}
                        <li>
                            <span>
                                <a href="{% relative_url object_list.next_page_number 'page' request.GET.urlencode %}">
                                    Next
                                </a>
                            </span>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

{% block jsout %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        function showError(element) {
            const errorMessage = $(element).data('object-value');
            Swal.fire({
                icon: 'error',
                title: 'Error Reason',
                text: errorMessage
            });
        }
    </script>

    <script>
        $(document).ready(function () {
            $('label').hide();
            $('input').addClass('form-control form-control-lg bg-inverse bg-opacity-5');
            $('select').addClass('form-select');
            $("#id_recipient").attr("placeholder", "Enter Recipient Email");
            $("#id_status option:first").text("-- Select Status --");
        });
    </script>
{% endblock %}