root/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.views.static import serve

from root.settings import ENVIRONMENT, MEDIA_ROOT, STATIC_ROOT
from src.core.handlers import (
    handler404, handler500
)

urlpatterns = []

""" HANDLERS ------------------------------------------------------------------------------------------------------- """
handler404 = handler404
handler500 = handler500

""" INTERNAL REQUIRED APPS ----------------------------------------------------------------------------------------- """
urlpatterns += [
    path('', include('src.web.urls')),
    path('', include('src.api.urls')),
    path('', include('src.apps.whisper.urls')),
]

""" EXTERNAL REQUIRED APPS ----------------------------------------------------------------------------------------- """
urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),

]

""" STATIC AND MEDIA FILES ----------------------------------------------------------------------------------------- """
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

""" DEVELOPMENT ONLY -------------------------------------------------------------------------------------------- """
if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

    urlpatterns += [
        path('', TemplateView.as_view(template_name='dev/starter-page.html')),  # use: for home page/remove this
    ]

src/web/admins/urls.py
from django.urls import path
from .views import (
    DashboardView,
    UserListView, UserPasswordResetView, UserDetailView, UserUpdateView, SocialsView, remove_social_account
)


app_name = 'admins'
urlpatterns = [

    path('', DashboardView.as_view(), name='dashboard'),

    path('user/', UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/change/', UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/password/reset/', UserPasswordResetView.as_view(), name='user-password-reset-view'),

    path('socials/', SocialsView.as_view(), name='social-accounts'),
    path('remove-social-auth/<int:account_id>/', remove_social_account, name='remove_social_account'),

]

src/web/admins/templates/admins/include/admin_header.html
<div class="topnav">
    <div class="container-fluid">
        <nav class="navbar navbar-light navbar-expand-lg topnav-menu">

            <div class="collapse navbar-collapse" id="topnav-menu-content">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link dropdown-toggle arrow-none" href="{% url 'admins:dashboard' %}">
                            <i class="bx bx-home-circle mr-2"></i>Dashboard
                        </a>
                    </li>


                    {# Apps #}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-pages" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="bx bx-user mr-2"></i>User Control
                            <div class="arrow-down"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="topnav-pages">
                            <a href="{% url 'admins:user-list' %}" class="dropdown-item">Users</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>

src/web/admins/templates/admins/include/admin_nav.html
{% load static %}
{#{% load notifications_tags %}#}

<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <!-- LOGO -->
            <div class="navbar-brand-box">
                <a href="#" class="logo logo-dark">
                                <span class="logo-sm">
                                    <img src="{% if app.logo %}{{ app.logo.url }}{% else %}{% static 'core/images/logos/logo-red.png' %}{% endif %}" alt="" height="35">
                                </span>
                    <span class="logo-lg">
                                    <img src="{% if app.logo %}{{ app.logo.url }}{% else %}{% static 'core/images/logos/logo-red.png' %}{% endif %}" alt="" height="35">
                                </span>
                </a>

                <a href="#" class="logo logo-light">
                                <span class="logo-sm">
                                    <img src="{% if app.logo %}{{ app.logo.url }}{% else %}{% static 'core/images/logos/logo-red.png' %}{% endif %}" alt="" height="35">
                                </span>
                    <span class="logo-lg">
                                    <img src="{% if app.logo %}{{ app.logo.url }}{% else %}{% static 'core/images/logos/logo-red.png' %}{% endif %}" alt="" height="35">
                                </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 d-lg-none header-item waves-effect waves-light"
                    data-toggle="collapse" data-target="#topnav-menu-content">
                <i class="fa fa-fw fa-bars"></i>
            </button>

        </div>

        <div class="d-flex">

            {# FULL_SCREEN #}
            <div class="dropdown d-none d-lg-inline-block ml-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="fullscreen">
                    <i class="bx bx-fullscreen"></i>
                </button>
            </div>

            {# NOTIFICATIONS #}
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect"
                        id="page-header-notifications-dropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="bx bx-bell bx-tada"></i>
                    <span class="badge badge-danger badge-pill">
{#                        {% live_notify_badge %}#}
                    </span>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0"
                     aria-labelledby="page-header-notifications-dropdown">
                    <div class="p-3">
                        <div class="row align-items-center">
                            <div class="col">
                                <h6 class="m-0"> Notifications </h6>
                            </div>
                            <div class="col-auto">
                                <a href="#" class="small"> View All</a>
                            </div>
                        </div>
                    </div>
                    <div data-simplebar style="max-height: 420px;">
                        <div id="notify_me_now">

                        </div>
                        <div class="p-2 border-top text-center">
                            <button class="btn text-primary small" onclick="unread_all_notifications()">
                                <i class="mdi mdi-arrow-right-circle mr-1"></i> Mark All as Read
                            </button>
                        </div>
                    </div>
                </div>

            </div>

            {#            <div class="dropdown d-inline-block">#}
            {#                <button type="button" class="btn header-item noti-icon right-bar-toggle waves-effect">#}
            {#                    <i class="bx bx-cog bx-spin"></i>#}
            {#                </button>#}
            {#            </div>#}


            {# USER ONLINE #}
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user"
                            {% if request.user.profile_image %}
                         src="{{ request.user.profile_image.url }}"
                            {% else %}
                         src="{% static 'core/images/base/no-user.png' %}"
                            {% endif %}
                         alt="Header Avatar">
                    <span class="d-none d-xl-inline-block ml-1">{{ request.user.username }}</span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <!-- item-->
                    <a class="dropdown-item" href="{% url 'accounts:cross-auth' %}">
                        <i class="bx bxs-dashboard font-size-16 align-middle mr-1"></i> Dashboard
                    </a>
                    <a class="dropdown-item" href="{% url 'accounts:user-change' %}">
                        <i class="bx bx-user font-size-16 align-middle mr-1"></i> Profile
                    </a>
                    <div class="dropdown-divider"></div>

                    <a class="dropdown-item" href="{% url 'account_email' %}">
                        <i class="bx bxl-telegram font-size-16 align-middle mr-1"></i> Email accounts
                    </a>
                    <a class="dropdown-item" href="{% url 'account_change_password' %}">
                        <i class="bx bx-lock-open font-size-16 align-middle mr-1"></i>Password Change
                    </a>
                    <a class="dropdown-item" href="{% url 'admins:social-accounts' %}">
                        <i class="bx-fw bx bxl-facebook-square font-size-16 align-middle mr-1"></i>Social Accounts
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-primary" href="{% url 'accounts:logout' %}">
                        <i class="bx bx-power-off font-size-16 align-middle mr-1"></i> Logout
                    </a>
                </div>
            </div>

        </div>
    </div>
</header>

{% if request.user.is_superuser %}
    {% include 'admins/include/admin_header.html' %}
{% endif %}